---
# setup repo
- hosts: all
  gather_facts: true
  become: true
  roles:
  - common

# setup LB
- hosts: frontends
  gather_facts: true
  become: true
  roles:
  - lb-tier

# setup LB
- hosts: apps
  gather_facts: true
  become: true
  roles:
  - web-tier

